### ISSUE TITLE
qgis_ja.qmの場所

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [isaomatsunami/QGIS3.14Japanese#1]
お疲れ様です。
FOSS4G TOKAIの吉中です。
環境によって違う可能性はありますし、細かいところで蛇足となりますが
Windows版の場合入れ替え先フォルダは
C¥Program Files¥QGIS 3.14¥apps¥qgisi18n
ではなく、
C:\Program Files\QGIS 3.14\apps\qgis\i18n
のほうだと思われます。（qgisフォルダの下にi18nフォルダがある。）

**Comment by isaomatsunami** [comment]
ご指摘ありがとうございます。直しました。
